FROM node:20-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# متغیرهای public در زمان build داخل bundle قرار می‌گیرند و secret محسوب نمی‌شوند.
ARG NEXT_PUBLIC_APP_NAME="آکادمی نوشیروانی"
ARG NEXT_PUBLIC_APP_SHORT_NAME="نوشیروانی"
ARG NEXT_PUBLIC_APP_DESCRIPTION="سامانه مدیریت آزمون و مشاوره تحصیلی آکادمی نوشیروانی"
ARG NEXT_PUBLIC_APP_VERSION="0.1.0"
ARG NEXT_PUBLIC_APP_ENV="production"
ARG NEXT_PUBLIC_SITE_URL="http://localhost"
ARG NEXT_PUBLIC_API_BASE_PATH="/api/v1"
ARG NEXT_PUBLIC_LOCALE="fa-IR"
ARG NEXT_PUBLIC_TIME_ZONE="Asia/Tehran"
ARG NEXT_PUBLIC_SUPPORT_EMAIL="support@noshirvaniacademy.com"
ARG NEXT_PUBLIC_SUPPORT_PHONE="+981112345678"
ARG NEXT_PUBLIC_INSTAGRAM_URL=""
ARG NEXT_PUBLIC_TELEGRAM_URL=""
ARG NEXT_PUBLIC_QUERY_STALE_TIME_MS="60000"
ARG NEXT_PUBLIC_QUERY_GC_TIME_MS="600000"
ARG NEXT_PUBLIC_QUERY_RETRY_COUNT="1"
ARG NEXT_PUBLIC_QUERY_REFETCH_ON_WINDOW_FOCUS="false"
ARG NEXT_PUBLIC_OTP_RESEND_SECONDS="120"
ARG NEXT_PUBLIC_DEFAULT_PAGE_SIZE="20"
ARG NEXT_PUBLIC_PROFILE_UPLOAD_MAX_MB="10"
ARG NEXT_PUBLIC_DOCUMENT_UPLOAD_MAX_MB="50"
ARG NEXT_PUBLIC_MULTIPLE_UPLOAD_MAX_FILES="10"
ARG NEXT_PUBLIC_ENABLE_BLOG="true"
ARG NEXT_PUBLIC_ENABLE_CONTACT_PAGE="true"
ARG NEXT_PUBLIC_ENABLE_QUERY_DEVTOOLS="false"
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
