FROM node:22-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --global npm@11.17.0 --no-audit --no-fund
RUN --mount=type=cache,id=noshirvani-npm-v2,target=/root/.npm npm ci --no-audit --no-fund --prefer-offline

FROM node:22-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Public values are compiled into the browser bundle. They configure presentation and behavior and must never contain secrets.
ARG NEXT_PUBLIC_APP_NAME="آینده سبز"
ARG NEXT_PUBLIC_APP_SHORT_NAME="آینده سبز"
ARG NEXT_PUBLIC_APP_DESCRIPTION="پلتفرم تحلیل عملکرد درسی دانش آموزان کنکوری"
ARG NEXT_PUBLIC_APP_VERSION="0.1.0"
ARG NEXT_PUBLIC_SITE_URL="http://localhost"
ARG NEXT_PUBLIC_API_BASE_PATH="/api/v1"
ARG NEXT_PUBLIC_LOCALE="fa-IR"
ARG NEXT_PUBLIC_TIME_ZONE="Asia/Tehran"
ARG NEXT_PUBLIC_SUPPORT_EMAIL="support@example.com"
ARG NEXT_PUBLIC_SUPPORT_PHONE="+980000000000"
ARG NEXT_PUBLIC_INSTAGRAM_URL=""
ARG NEXT_PUBLIC_TELEGRAM_URL=""
ARG NEXT_PUBLIC_QUERY_STALE_TIME_MS="60000"
ARG NEXT_PUBLIC_QUERY_GC_TIME_MS="600000"
ARG NEXT_PUBLIC_QUERY_RETRY_COUNT="1"
ARG NEXT_PUBLIC_QUERY_REFETCH_ON_WINDOW_FOCUS="false"
ARG NEXT_PUBLIC_OTP_RESEND_SECONDS="120"
ARG NEXT_PUBLIC_DEFAULT_PAGE_SIZE="20"
ARG NEXT_PUBLIC_PROFILE_UPLOAD_MAX_MB="10"
ARG NEXT_PUBLIC_DOCUMENT_UPLOAD_MAX_MB="50"
ARG NEXT_PUBLIC_MULTIPLE_UPLOAD_MAX_FILES="10"
ARG NEXT_PUBLIC_ENABLE_BLOG="true"
ARG NEXT_PUBLIC_ENABLE_CONTACT_PAGE="true"
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME \
    NEXT_PUBLIC_APP_SHORT_NAME=$NEXT_PUBLIC_APP_SHORT_NAME \
    NEXT_PUBLIC_APP_DESCRIPTION=$NEXT_PUBLIC_APP_DESCRIPTION \
    NEXT_PUBLIC_APP_VERSION=$NEXT_PUBLIC_APP_VERSION \
    NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_API_BASE_PATH=$NEXT_PUBLIC_API_BASE_PATH \
    NEXT_PUBLIC_LOCALE=$NEXT_PUBLIC_LOCALE \
    NEXT_PUBLIC_TIME_ZONE=$NEXT_PUBLIC_TIME_ZONE \
    NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL \
    NEXT_PUBLIC_SUPPORT_PHONE=$NEXT_PUBLIC_SUPPORT_PHONE \
    NEXT_PUBLIC_INSTAGRAM_URL=$NEXT_PUBLIC_INSTAGRAM_URL \
    NEXT_PUBLIC_TELEGRAM_URL=$NEXT_PUBLIC_TELEGRAM_URL \
    NEXT_PUBLIC_QUERY_STALE_TIME_MS=$NEXT_PUBLIC_QUERY_STALE_TIME_MS \
    NEXT_PUBLIC_QUERY_GC_TIME_MS=$NEXT_PUBLIC_QUERY_GC_TIME_MS \
    NEXT_PUBLIC_QUERY_RETRY_COUNT=$NEXT_PUBLIC_QUERY_RETRY_COUNT \
    NEXT_PUBLIC_QUERY_REFETCH_ON_WINDOW_FOCUS=$NEXT_PUBLIC_QUERY_REFETCH_ON_WINDOW_FOCUS \
    NEXT_PUBLIC_OTP_RESEND_SECONDS=$NEXT_PUBLIC_OTP_RESEND_SECONDS \
    NEXT_PUBLIC_DEFAULT_PAGE_SIZE=$NEXT_PUBLIC_DEFAULT_PAGE_SIZE \
    NEXT_PUBLIC_PROFILE_UPLOAD_MAX_MB=$NEXT_PUBLIC_PROFILE_UPLOAD_MAX_MB \
    NEXT_PUBLIC_DOCUMENT_UPLOAD_MAX_MB=$NEXT_PUBLIC_DOCUMENT_UPLOAD_MAX_MB \
    NEXT_PUBLIC_MULTIPLE_UPLOAD_MAX_FILES=$NEXT_PUBLIC_MULTIPLE_UPLOAD_MAX_FILES \
    NEXT_PUBLIC_ENABLE_BLOG=$NEXT_PUBLIC_ENABLE_BLOG \
    NEXT_PUBLIC_ENABLE_CONTACT_PAGE=$NEXT_PUBLIC_ENABLE_CONTACT_PAGE
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:22-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

USER nextjs

EXPOSE 3000
CMD ["node", "server.js"]
