export type EndpointAccess = "public" | "authenticated" | "admin";
export type EndpointContract = { method: "GET" | "POST" | "PUT" | "DELETE"; path: string; access: EndpointAccess; response: string; notes?: string };

// inventory قابل پردازش تمام routeهای ثبت‌شده در router.go؛ مبنای fixture و تست پوشش قرارداد.
export const endpointContracts = [
  { method: "GET", path: "/health", access: "public", response: "HealthResponse" },
  { method: "POST", path: "/auth/request-otp", access: "public", response: "OtpResponse" },
  { method: "POST", path: "/auth/verify-otp", access: "public", response: "AuthResponse" },
  { method: "POST", path: "/auth/refresh", access: "public", response: "RefreshResponse" },
  { method: "GET", path: "/blog", access: "public", response: "BlogPost[]", notes: "فقط published" },
  { method: "GET", path: "/blog/:slug", access: "public", response: "BlogPost" },
  { method: "GET", path: "/subjects?major=", access: "public", response: "SubjectConfig" },
  { method: "GET", path: "/majors", access: "public", response: "SubjectConfig[]" },
  { method: "POST", path: "/students/profile", access: "authenticated", response: "Student" },
  { method: "GET", path: "/students/profile", access: "authenticated", response: "Student" },
  { method: "POST", path: "/exams", access: "authenticated", response: "Exam" },
  { method: "GET", path: "/exams", access: "authenticated", response: "Exam[]" },
  { method: "GET", path: "/exams/:id", access: "authenticated", response: "Exam" },
  { method: "PUT", path: "/exams/:id", access: "authenticated", response: "Exam", notes: "subjects کامل replace می‌شود" },
  { method: "DELETE", path: "/exams/:id", access: "authenticated", response: "StatusResponse" },
  { method: "POST", path: "/mistakes", access: "authenticated", response: "Mistake" },
  { method: "GET", path: "/mistakes", access: "authenticated", response: "Mistake[]" },
  { method: "PUT", path: "/mistakes/:id", access: "authenticated", response: "Mistake" },
  { method: "DELETE", path: "/mistakes/:id", access: "authenticated", response: "StatusResponse" },
  { method: "GET", path: "/students/performance", access: "authenticated", response: "PerformanceHistory[]" },
  { method: "GET", path: "/students/statistics?from=&to=", access: "authenticated", response: "ExamStatistics" },
  { method: "GET", path: "/students/dashboard", access: "authenticated", response: "DashboardSummary" },
  { method: "POST", path: "/upload?type=", access: "authenticated", response: "UploadResponse" },
  { method: "POST", path: "/upload/multiple?type=", access: "authenticated", response: "UploadResponse[]" },
  { method: "GET", path: "/admin/students", access: "admin", response: "Student[]", notes: "حداکثر ۱۰۰؛ UI از with-stats استفاده کند" },
  { method: "GET", path: "/admin/students/with-stats?page=&limit=&approved=", access: "admin", response: "PaginatedResponse<StudentWithStats>" },
  { method: "GET", path: "/admin/students/:id", access: "admin", response: "Student" },
  { method: "GET", path: "/admin/students/:id/exams", access: "admin", response: "Exam[]" },
  { method: "GET", path: "/admin/students/:id/mistakes", access: "admin", response: "Mistake[]" },
  { method: "PUT", path: "/admin/students/:id", access: "admin", response: "StatusResponse" },
  { method: "PUT", path: "/admin/students/:id/approve", access: "admin", response: "StatusResponse" },
  { method: "DELETE", path: "/admin/students/:id", access: "admin", response: "StatusResponse" },
  { method: "GET", path: "/admin/students/:id/performance", access: "admin", response: "PerformanceHistory[]" },
  { method: "POST", path: "/admin/students/:id/performance", access: "admin", response: "PerformanceHistory" },
  { method: "PUT", path: "/admin/performance/:id", access: "admin", response: "StatusResponse" },
  { method: "DELETE", path: "/admin/performance/:id", access: "admin", response: "StatusResponse" },
  { method: "GET", path: "/admin/students/:id/statistics?from=&to=", access: "admin", response: "ExamStatistics" },
  { method: "GET", path: "/admin/dynamic-fields?entity_type=", access: "admin", response: "DynamicFieldDefinition[]" },
  { method: "POST", path: "/admin/dynamic-fields", access: "admin", response: "DynamicFieldDefinition" },
  { method: "PUT", path: "/admin/dynamic-fields/:id", access: "admin", response: "StatusResponse" },
  { method: "DELETE", path: "/admin/dynamic-fields/:id", access: "admin", response: "StatusResponse" },
  { method: "GET", path: "/admin/blog", access: "admin", response: "BlogPost[]" },
  { method: "POST", path: "/admin/blog", access: "admin", response: "BlogPost", notes: "فعلاً HTTP 200 نه 201" },
  { method: "PUT", path: "/admin/blog/:id", access: "admin", response: "StatusResponse" },
  { method: "PUT", path: "/admin/blog/:id/publish", access: "admin", response: "StatusResponse" },
  { method: "DELETE", path: "/admin/blog/:id", access: "admin", response: "StatusResponse" },
] as const satisfies readonly EndpointContract[];
